services:
  app:
   
    image: noorum/wanderlust-app:latest
    container_name: wanderlust-app

    env_file:
      - .env

    ports:
      - "8080:8080"

    restart: unless-stopped

    init: true
networks:
  wanderlust-network:
    driver: bridge
