apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  namespace: ghost-app
spec:
  type: NodePort
  selector:
    app: ghost
  ports:
    - port: 80
      targetPort: 2368
      nodePort: 32368